const data = {
  products: [
    {
      name: 'RedHeaven Tshirt',
      slug: 'redheaven-tshirt',
      category: 'Tshirt',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'ArtBoard',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Tshirt with Red Heaven Illustration.',
    },
    {
      name: 'IUT Cat Tshirt',
      slug: 'iut-cat-tshirt',
      category: 'Tshirt',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'ArtBoard',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Tshirt with Illustration.',
    },
    {
      name: 'IUT Tshirt',
      slug: 'iut-tshirt',
      category: 'Tshirt',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'ArtBoard',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Tshirt with Illustration.',
    },
    {
      name: 'Tshirt',
      slug: 'tshirt',
      category: 'Tshirt',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'ArtBoard',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Tshirt with Illustration.',
    },
  ],
};

export default data;
